### ISSUE TITLE
format function in t function

### ISSUE THREAD

**Issue by LaurentGoderre** [i18next/i18next#1034]
From the doc, the following should be working:

```
i18next.t("key", {
    interpolation: {
        format: function(){...}
    }
})
```

But for some reason the format function never gets called

**Comment by jamuhl** [comment]
what is the translation of key?

**Comment by jamuhl** [comment]
both the format and escape function can only be set on i18next.init

**Comment by LaurentGoderre** [comment]
And modifying the `i18next.options.interpolation.format` after the fact doesn't work either does it?

**Comment by jamuhl** [comment]
nope

**Comment by LaurentGoderre** [comment]
Thanks!

**Comment by jamuhl** [comment]
if you need a option to reset it or append via t options let me know

**Comment by LaurentGoderre** [comment]
No. I should follow the proper way. It wouldn't be that hard. I was just trying to move fast.

**Comment by jamuhl** [comment]
ok great...if there is anything else or you change your mind...let me know.

**Comment by mir3z** [comment]
> both the format and escape function can only be set on i18next.init

So could you at least update the docs?

If this isn't working then what's the proper way of setting a very specific one-time formatter? Should I include them in big switch statement in `format` function during initialization?

**Comment by jamuhl** [comment]
@mir3z we could support that if important to you...but the preferred way would be to only pass those on init (simplifies also your `t` calls in your code base - but might be a matter of taste)

**Comment by mir3z** [comment]
Agree, simply speaking each approach has it's own pros and cons. If you put everything in `init` you may end up with bloated `format` func where some formatters are only used once, see my point:

```javascript
const formatter = (value, format, lng) => {
    switch (format) {
        case "uppercase": return ...
        case "number": return Intl.NumberFormat(lng).format(val)
        case "number_anotherway": return ...
        case "number_anotherway2": return ...
        case "foo": return ...
        ...
    }

    return moment(value).format(format);
};
```

The thing that may help would be to provide additional parameters to `format` function (I think I saw an issue for that), because currently the only way of parametrization is via `format` arg which is not always sufficient.

**Comment by jamuhl** [comment]
@mir3z open for suggestions or even PR

**Comment by diesl** [comment]
I was also trying to set the formatter after init, but had to learn this is not (yet) possible. Let me show you my use case:

I want to show prices that are stored in a database, and these prices can have different currencies. Sometimes I have to set some more options for the prices too, but that is not really important here. So I set up a formatter for each currency style:
```coffeescript
format: (value, format, lng) ->
  if (format == 'EUR')
    return new Intl.NumberFormat(lng, { style: 'currency', currency: 'EUR' }).format(value)
  else if (format == 'EUR-long')
    return new Intl.NumberFormat(lng, { style: 'currency', currency: 'EUR', minimumFractionDigits: 3 }).format(value)
  ...
```

Because the currency (and therefore the format) is stored in the database, I wanted to append the format to the key:

```coffeescript
t('key', { price: value, interpolation: { format: currency } });
```

As a "workaround" I use this code from #774 but it is not that pretty in my opinion:
```coffeescript
$.t('key', { price: i18next.options.interpolation.format(value, currency, lng) });
```

What do you think? I am not sure if this can be done in another way, but after working on a problem for a while it is hard to see the wood for the trees ...

**Comment by jamuhl** [comment]
guess it would need a change here to pass additional options like format to interpolate function: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L74

Which gets called here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L194
