### ISSUE TITLE
Autoloading of Namespaces

### ISSUE THREAD

**Issue by dnauck** [i18next/i18next#109]
Hello,

as also asked on StackOverflow [1] it would be nice to let i18next auto load missing namespaces from the server.

This is perfectly for scenarios with `dynamicLoad: true` and REST services that providing the resouces.

[1] http://stackoverflow.com/questions/13210978/autoloading-of-namespaces-i18next

**Comment by vituchon** [comment]
I find thiss @jamuhl and it happens I just thought the same => https://stackoverflow.com/questions/13210978/autoloading-of-namespaces-i18next#comment130490838_13701183. I mean having this functionallity implies to change the actual signature of t method... not backwards compliant :worried: .

I guess this change is not easy as I far understand this thing, i18next is not capable of loading external files (hence there is no room for namespaces existance, as they should be one or more files as the doc states) so you probably need to work with i18next-[backend|http|fetch|other] that actually performs the loading. Well actually don't know that, just assuming. 

Very nice piece of software what you have done! keep up the good work! Thanks for making it available!

Greetings
Víctor

Attachment _statement on documentation about namespaces_

![image](https://user-images.githubusercontent.com/1927644/193158563-67331057-06da-4f8a-ae99-d5e5e2e1fc10.png)

**Comment by jamuhl** [comment]
@vituchon that's a very old issue but still holds true.

The `t` function can't really be responsible for asserting that translations are loaded before returning that translation (key from JSON). To do so the `t` function would have either to be blocking (no go!) or async using a callback or promise which would just make using that API a lot harder as all your UI code needs to wait for the resolve of those promises...

That's why `t` is NOT responsible for loading and asserting translations exist.

To solve the problem namespaces should be loaded per page, per component, per section using the build in loadNamespaces and hasLoadedNamespaces check:

- https://github.com/i18next/i18next/blob/master/src/i18next.js#L417
- https://github.com/i18next/i18next/blob/master/src/i18next.js#L457

for react-i18next we eg. got: https://react.i18next.com/latest/usetranslation-hook for loading namespaces onDemand

**Comment by vituchon** [comment]
Hi @jamuhl thanks for the quick reply, nice to be in touch with someone in the other side.

In our system we use both angularjs and react for the front. For both we are employing i18next as primary tool for dealing with i18n affairs. We augment i18next "natural" capabilities with the benefits that ng-18next and react-18next provides. Also we use i18next-http-backend for loading translation files instead of having the translations hardcoded in the javascript/typescript code.

I have found a way to "deal" with this issue on angularjs, using the ui-route pluging, there is a property for each web page (a.k.a. "state" in "ng-route" ir "ui-route" proyect domains) called ["resolve"](https://ui-router.github.io/ng1/tutorial/hellosolarsystem#resolve-data) and that is a place where you can put code for doing things BEFORE landing on a given page or subset of pages... so that really should work (currently I'm working on it) to load the translations' namespace required for the page the user is about to see/navigate into. If you are interesting on see more, I can gladly share some code with you.

I have no clue how to do it in react yet, (react is still a pending thing to study and get in deep), but your advices may work for the project and for me as well.

Thanks again.
Greetings

Vïctor.

**Comment by jamuhl** [comment]
As we personally use react over angular (and angular comes with an own solution for i18n it is directing i18next to a second option) the implementation for react is more worked on. So leaving some code snippets here (or doing a little blog post) would help others considering using ng-i18next.

Regarding react-i18next following the samples should get you started in no time: https://react.i18next.com/latest/using-with-hooks (includes lng detection, http-backend).

Or read the starting guide on our translation management platform locize.com -> https://locize.com/blog/react-i18next/ that one goes rather deep.

**Comment by vituchon** [comment]
@jamuhl Thanks again for your valuable feedback/insight on this!. I have noticed or, at least have the felling, that currently there is more content and articles regarding i18next for react than for angularjs, it have sense, as angularjs is not maintained anymore in now-a-days.

I'm trying to reach the guys of ng-i18next as their implementation have already another problem I have ran into and sorted it out, I have filed a ticket in [this issue](https://github.com/i18next/ng-i18next/issues/165). I will glady share more solutions and insight on making things works legacy angularjs, for those that pledged to angularjs in the ancient times of web development and now are condemned to keep the vows of fidelity as the front is powered using that technology.

Keep up the good work!
Greetings
Víctor
