### ISSUE TITLE
angular-i18next: Reduce the number of implementations - join the forces on one implementation

### ISSUE THREAD

**Issue by jamuhl** [i18next/i18next#1126]
i18next goal was always to be usable in all the UI frameworks out there. While i18next got a wide adoption and react-i18next (https://github.com/i18next/react-i18next) got very popular we struggle in being successful on angular.js.

One main problem I currently see there are three implementations developers can choose from. This spreads activity, adds the burden of having to choose on devs and make doing "marketing" for those harder.

I really would love to see i18next being more successful in the angular.js community.

So I would love to have your inputs on:

Would it make sense to join all the implementations (contributors/maintainers) to one "more official" implementation optionally under i18next organization? Would you be willing to help with code, documentation, samples, tweets, medium posts, ...?
Do you have ideas on how to spread the word more?
...

**Comment by jamuhl** [comment]
@bugwelle @bloveridge @anwalkers @actimeo @feloy @romanchuk

**Comment by Romanchuk** [comment]
@jamuhl Hi! I aggree that it would be great if there would be one official implementation. And i'm ready to cooperate.

Before we start I think we should separate angular.js and angular since v2. These are completelly different frameworks and i think there is no sense to make single implementation for both (That is why 
 my implementations supports only v2+).

[angular-i18next](https://www.npmjs.com/package/angular-i18next) was implemented because at the moment i started work with angular 2 there was no implementation that support AOT compile or event handling. And some implementations had there own options on top of native i18next options. My ideology to make people use library as simple as they would use original i18next (so they can read original docs and do anything it says) and add some angular specific features as: pipes for templates (i18next and i18nextFormat), load on angular initialize live cycle event, rxjs event handling, lazy loading, init error handling strategy.

Also i implemented other "helper" packages to integrate angular and i18next more deeply and i'm actively using them in my projects:

- [angular-validation-message](https://github.com/Romanchuk/angular-validation-message) - localizer for angular [reactive form validators(https://angular.io/guide/reactive-forms#step-2-making-a-field-required) (and [angular-validation-message-i18next ](https://github.com/Romanchuk/angular-validation-message-i18next) is i18next bridge to it). It gives you possibility to localize form validators and it automatically puts localized validator error message to markup (if there is one).
- [angular-i18next-error-interceptor](https://github.com/LCGroupIT/angular-i18next-error-interceptor) - allows you to set default errot messages for non-200 http status responses. So if the back-end didn't specify { message: 'some error' } in a response (sort of contract with our backend) interceptor will check response status code and will fill { message: 'Server is not available. Please try again.' }. Also package includes pipe where you can pass HttpErrorResponse and it will return error message whenever it's back-end message or our localized message.

Before you wrote, I had plan to make an article on russian about localizing angular  =) relying on experiense of implementing angular-i18next and other helper packages. Didn't start it yet)
