### ISSUE TITLE
Plural with arrays

### ISSUE THREAD

**Issue by aswetlow** [i18next/i18next#1196]
Hey!

I may misunderstand something, but I can't get plurals to work with arrays.

Steps to reproduce:
```javascript
const i18next = require('i18next');

i18next.init({
    lng: 'en',
    returnObjects: true,
    resources: {
        en: {
            translation: {
                "keyArray": ["hello world {{count}}", "hey {{count}}"],
                "keyArray_plural": ["hello world plural {{count}}", "hey plural {{count}}"],
            }
        }
    }
});
console.log(i18next.t('keyArray', {count: 1}));
console.log(i18next.t('keyArray', {count: 3}));
```

What I expect:
```
[ 'hello world 1', 'hey 1' ]
[ 'hello world plural 3', 'hey plural 3' ]
```

What I get:
```
[ 'hello world 1', 'hey 1' ]
[ 'hello world 3', 'hey 3' ]
```

Thanks in advance!

**Comment by jamuhl** [comment]
It runs through all the items in the array or object -> https://github.com/i18next/i18next/blob/master/src/Translator.js#L131 (to assert those inner values in the object, array, get interpolated, postprocessed,...)

which result in taking `keyArray.0` and `keyArray.1` in this case as no `keyArray.0_plural` and `keyArray.1_plural` exist.

a possible fix might be changing https://github.com/i18next/i18next/blob/master/src/Translator.js#L133 setting resUsedKey to _plural (or correct suffix based on language and count) if is array and has count in options.

While i agree this is an issue - i must say this is a rather edge case use case -> what's the idea behind using an array here instead of 2 keys?

**Comment by aswetlow** [comment]
Thanks for the quick reply. We at @jovotech work on a framework for voice apps (Alexa Skills, Google Actions) were we integrated i18next (Thank you for the great library!!!)
Variability in output is very important in voice. Voice assistants who answer the same simple phrases all the time are kind of boring. We have helper methods that pick a random translation for a key from an array.

Example:
```
// translation
 "WELCOME": [
      "Welcome",
      "Hey",
      "Hello"
    ]
```
Usage in code
```javascript
let speech = this.speechBuilder().addT('WELCOME');
this.tell(speech); // Alexa says "Welcome", "Hey" or "Hello"
```
[Docs: Jovo with i18next](https://www.jovo.tech/docs/output/i18n)

This works perfectly fine! Would be cool if it worked with plural with arrays, too.

**Comment by jamuhl** [comment]
Ok i see...seems to make sense. Currently i'm hard on time - so might take me a few days to get that in.

If you feel confortable enough with the i18next codebase you might try a PR to speed this up...but not an easy one as needs to work for all pluralforms...

**Comment by aswetlow** [comment]
Indeed, not an easy one :) I'm afraid I don't have an overview for such a task. 

There's no hurry. Thank you!

**Comment by jamuhl** [comment]
could you try with i18next@14.1.0

**Comment by aswetlow** [comment]
Works perfectly! Thank you!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
