### ISSUE TITLE
Languages with multiple plurals not working 

### ISSUE THREAD

**Issue by ad1992** [i18next/i18next#1209]
https://www.i18next.com/translation-function/plurals

Hi I am using the below keys in my local file as given in the docs https://www.i18next.com/translation-function/plurals

```
{
     "key": "none",
     "key_0": "zero",
      "key_1": "singular",
      "key_2": "two",
      "key_3": "few",
      "key_4": "many",
      "key_5": "other"
}
```
However 
```
i18next.t('key', {count: 0}); // -> "none"

```
Be it any value of count, I always get `none`
And if i remove `"key": "none",` from the file then I get the error `i18next::translator: missingKey `

Is there anything I am missing ?

**Comment by jamuhl** [comment]
what language is i18next set to?

**Comment by ad1992** [comment]
@jamuhl the language is set to `en`

**Comment by jamuhl** [comment]
`en` has plural like:

```js
 {
     "key": "singular",
     "key_plural": "other",
}
```

**Comment by jamuhl** [comment]
the above sample is for Arabic - it even says so in the docs...

**Comment by ad1992** [comment]
@jamuhl got it. Thanks a lot for the quick reply. 
I got confused a bit with the docs . May be if a line is added `This is supported only in arabic` then that might help.

**Comment by jamuhl** [comment]
This is supported only in arabic --> the point is - there are a lot of languages and different rules...therefore depending on language check https://www.i18next.com/translation-function/plurals#how-to-find-the-correct-plural-suffix to get the needed suffixes

or use our https://locize.com which does automatically convert plurals from source to target language

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by ad1992** [comment]
@jamuhl the library is awesome !!. I have been using it in my projects.  Will check https://locize.com as well.

**Comment by doriclaudino** [comment]
**from documentation:**
Sample uses arabic which has 5 plural forms beside the singular.

**simplifyPluralSuffix** 
will use 'plural' as suffix for languages only having 1 plural form, setting it to false will suffix all with numbers

**Using:**
using simplifyPluralSuffix = false
key_0: 'zero ({{count}})',
          key_1: 'singular ({{count}})',
          key_2: 'two ({{count}})',
          key_3: 'few ({{count}})',
          key_4: 'many ({{count}})',
          key_5: 'other ({{count}})',


### receiving:

- singular (0)
- zero(1)
- singular(2)
- singular(50)
- singular(100)



### How then I handled it? (pt)

- friend_zero: 'Nenhum amigo(a)',
- friend_zero_plural: 'Nenhum amigos(as)',
- friend_male_zero: 'Nenhum amigo',
- friend_male_zero_plural: 'Nao ha amigos',
- friend_female_zero: 'Nenhuma amiga',
- friend_female_zero_plural: 'Nao ha amigas',
- friend: 'Um amigo(a) ({{count}})',
- friend_plural: 'Uns amigos(as) ({{count}})',
- friend_male: 'Um amigo ({{count}})',
- friend_female: 'Uma amiga ({{count}})',
- friend_male_plural: '{{count}} amigos',
- friend_female_plural: '{{count}} amigas',
- neutral: 'neutro',
- female: 'feminino',
- male: 'masculino',

### How then I handled it? (en)

- friend_zero: 'None friend',
- friend_zero_plural: 'No friends',
- friend_male_zero: 'None boyfriend',
- friend_male_zero_plural: 'No boyfriends',
- friend_female_zero: 'None girlfriend',
- friend_female_zero_plural: 'No girlfriends',
- friend: 'A friend ({{count}})',
- friend_plural: '{{count}} friends ({{count}})',
- friend_male: 'A boyfriend ({{count}})',
- friend_female: 'A girlfriend ({{count}})',
- friend_male_plural: '{{count}} boyfriends',
- friend_female_plural: '{{count}} girlfriends',
- neutral: 'neutral',
- female: 'female',
- male: 'male',


```
//using key "friend"
//play with context, return 'zero' when 
var _gender_options = ['neutral', 'male', 'female']
var _count = 0
var _gender = _gender_options [0]

/**
is count !==0 then context: _gender
is count === 0 and gender === 'neutral' then context: 'zero'
is count === 0 and gender !== 'neutral' then context:  _gender + '_zero'
*/

i18n.t("friend",
            options={{
              context:
                _count  !== 0
                  ? _gender 
                  : _gender === 'neutral'
                  ? 'zero'
                  : _gender + '_zero',
              count: _count ,
            }}

```


Not sure what's is wrong (api? or documentation?)
Maybe because "plural" means more than one, but as developer make sense pass the count and leave the strings to translators

**Comment by jamuhl** [comment]
The point is plurals for germanic, romanic, ... languages have no explicit form for zero...it's either the plural or the singular form eg. en vs. fr: en uses plural, fr uses singular form for zero.

To use this special case for zero please look at: https://github.com/i18next/i18next-intervalPlural-postProcessor

**Comment by Undeadlol1** [comment]
How come suffix detection is not part of the library? How come it is not automatic?
This is really inconvenient

**Comment by jamuhl** [comment]
@Undeadlol1 again, zero is not part of the specification for plurals...eg. en has no special case for zero!!! it has "one" and "other" if you like having special treatments for zero use: https://github.com/i18next/i18next-intervalPlural-postProcessor that can add special handling for zero, intervals, ...

**Comment by Undeadlol1** [comment]
For anybody who came here looking for a quick solution, here is what worked for me:
```js
const suffix = i18n.services.pluralResolver.getSuffix(
   i18n.language,
   count,
)
t( `countTasksDueToday${suffix}`, { count });

const en = {
    countTasksDueToday: '{{count}} task available today',
    countTasksDueToday_plural: '{{count}} tasks available today'
}
const ru = {
    countTasksDueToday_0: '{{count}} задачa на сегодня',
    countTasksDueToday_1: '{{count}} задачи на сегодня',
    countTasksDueToday_2: '{{count}} задач на сегодня'
}
```
If your language has special cases getSuffix will return _0, _1 and so on.
If your language has no special cases (like English language) it will return undefined or "_plural".

**Comment by jamuhl** [comment]
@Undeadlol1 sorry, but I do not understand what you're explaining here...this is documented:

https://www.i18next.com/translation-function/plurals#singular-plural
https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals

and suffixed can be looked up with this tool:  https://www.i18next.com/translation-function/plurals#how-to-find-the-correct-plural-suffix

**Comment by Undeadlol1** [comment]
@jamuhl well turns out i didn't understood how prefixes work.
I thought "_1" prefix means "if count == 1, use _1 prefix". 
I don't know why this misunderstanding happened. I had a brain fart.

![image](https://barnabyisright.files.wordpress.com/2013/05/ashamedhead-in-hands.jpg)

**Comment by Undeadlol1** [comment]
Also, maybe documentation isn't clear enough?

**Comment by Undeadlol1** [comment]
Maybe documentation isn't clear enough?

**Comment by jamuhl** [comment]
@Undeadlol1 Maybe you got an idea - how to improve the documentation?

**Comment by Cristy94** [comment]
This is confusing.

For example, why does Romanian have 3 plural keys, why is it a different plural if it's over 20 (key_2 instead of key_1) ?

**Comment by jamuhl** [comment]
@Cristy94 because plural forms and languages in general are more complex than you think I guess. Not every language knows just singular and plural - simple as that. 

https://lingohub.com/blog/2019/02/pluralization/

but I can understand - it feels confusing when starting...

**Comment by Cristy94** [comment]
Ok, I got it, but in Romanian it only needs the 3rd form if you include the count number too, otherwise it is just as in English (singular or plural).I guess there is no easy way to define the plural if you know you will never add the count. In my case I will just duplicate `word_0` and `word_2`.Thanks for the help!On 14 Feb 2020 07:06, Jan Mühlemann <notifications@github.com> wrote:@Cristy94 because plural forms and languages in general are more complex than you think I guess. Not every language knows just singular and plural - simple as that.
https://lingohub.com/blog/2019/02/pluralization/
but I can understand - it feels confusing when starting...

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:

**Comment by chenasraf** [comment]
So if I want to, for example, have a text of "Created today", "Created yesterday" and "Created {{count}} days ago", I have to manage my own keys? Or am I missing something?
Using _0, _1 and _plural doesn't work - it always falls back to _plural or [null].

What's the proper solution to thism then?

**Comment by adrai** [comment]
@chenasraf you may have also a look at: https://github.com/i18next/i18next-intervalPlural-postProcessor

**Comment by chenasraf** [comment]
@jamuhl well that was one example, the point stands imo in others, such as "no eggs", "a couple of eggs", "{{count}} eggs".

@adrai that seems like a bit of an overkill, and the syntax is confusing and weird...

I ended up passing the `count` as `context` as well. That seems to have worked.

**Comment by mohitmorepatil** [comment]
Can someone please guide me on how to set default values for plurals in i18next-extract

**Comment by jamuhl** [comment]
please ask on the i18next-extract repo

**Comment by JaffParker** [comment]
Why limit the multiple plurals support? I'm trying to leverage that feature in English for another purpose (display different text, if count is 0) and then find out that it's limited to Arabic only... Can there be at least an option to enable this behavior for other languages?

**Comment by jamuhl** [comment]
You can either use: https://github.com/i18next/i18next-intervalPlural-postProcessor/

or try: https://github.com/i18next/i18next/issues/1220#issuecomment-654161038

**Comment by JaffParker** [comment]
@jamuhl context is actually pretty good, yeah
