### ISSUE TITLE
Support for tag template style of using t

### ISSUE THREAD

**Issue by vincaslt** [i18next/i18next#1348]
I have used https://github.com/ttag-org/ttag for a while in some projects, and even though they lack a lot of features i18next has, their style of calling the translate function is very nice. It could be adapted to i18next (I've done it for my own use to some extent).

Some examples of how that can look like:

```
t`key` => t('key')
t`key ${value}` => t('key {{k_0}}', {k_0: value}) // can't extract the identifier name in tagged literals without AST, thus assign an arbitrary key for the interpolated value
t`key ${{value}}` => t('key {{value}}', {value}) // object is never valid as an interpolated value, so it's first property could always be interpreted as a key for the value
```

It could also separate interpolated values from translation function options:

```
t(options)`key ${value}`
```

What do you think, could that be considered?

**Comment by jamuhl** [comment]
Supporting the style / options developer like was always something we embraced. So, there is nothing from my side that would say we should not allow using template strings next to the function call...just be aware a key can also contain whitespaces and there are a few options like plurals that might need to force writing `t(options)\`key ${value}\``

PR is very welcome...

**Comment by vincaslt** [comment]
I'll see what I can do when I have some time for this.

**Comment by jtheisen** [comment]
A minor related issue here is i18next's love for named (rather than positioned) replacements, which are a type safety nightmare (renaming the "name" in `t("your name is {{name}}")` breaks the translations). So people who insist on type safety (like me), can't use the `t` function anyway, and could write a wrapper that does address template tagging and safety issues at the same time.

**Comment by jamuhl** [comment]
@jtheisen so what would you prefer? can you please make some samples? And what safety issues you got...? Not sure but we escape interpolation values per default...so there won't be any XSS doors until you turn escaping off...

**Comment by jtheisen** [comment]
@jamuhl Safety as in type safety, not security. If you rename variables and those variable names are important to the stored translation texts, the translations will break. Positional identification of variables doesn't have that problem.

I wrote a wrapper that allows me to write `` tr`you-have-${x}-items` `` which translates to `t("you-have-{{1}}-items", { "1": x })`. So there's no danger breaking anything by renaming something.

**Comment by jamuhl** [comment]
@jtheisen I prefer `You moved {{count}} {{what}} into {{target}}.` instead of `You moved {{0}} {{1}} into {{2}}` <-- good luck with translating...tastes are different I guess...and i18next is flexible enough you were able to build your taste with it.

The non-typesafe also support things like `i18next.t('hello {{user.name}}', { user: { name: 'jamuhl'}})` or there is sprintf support for the ones prefering that -> https://github.com/i18next/i18next-sprintf-postprocessor.

If there is anything we could add to make i18next more suitable for your case I would love to accept a PR.

**Comment by jtheisen** [comment]
> You moved {{0}} {{1}} into {{2}} <-- good luck with translating...tastes are different I guess

Your thing is clearly better for translators, I just worry about the maintainability of my code more.

> If there is anything we could add to make i18next more suitable for your case I would love to accept a PR.

I can just use the wrapper, so there's no need.

**Comment by jamuhl** [comment]
closing for now due inactivity

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
