### ISSUE TITLE
exists() for nesting objects/arrays into objects

### ISSUE THREAD

**Issue by Apo-S** [i18next/i18next#1368]
When using a similar locale file

```json
{
    "objOne": {
        "keyOne": "value1",
        "keySecond": "value2",
    },
    "objSecond": {
        "key": "$t(objOne)"
    }
}
```

Then when I call the function `exists` like `exists('objSecond.key.keyOne')` I get `false`

#925

**Comment by jamuhl** [comment]
expected...that key does not exist -> you call `t('objSecond.key')` and get nothing meaningful...as you nest an object but if it would be `"key": "$t(objOne.keySecond)"` -> `value2`

**Comment by pranjalg8** [comment]
Hi, I have a similar case like above. Something like this 
`{
  "mario_strings1": {
    "default1": "payment"
  },
  "mario_strings2": {
    "default2": "Credit card"
  },
  "mario_strings3": {
    "default1": "seller"
  }
}` 
Here i know for a fact that the first id ie. "mario_strings1" in the first case will be a unique for each case, the second nested key ie. "default1" here is either "default1" or "default2" or essentially an item from an array of keys ["default1", "default2", ...], basically being known beforehand and limited. Given that the first keys are unique, is there a way to access them in a way like this `i18n.t("mario_strings1")` instead of `i18n.t("mario_strings1.default1")`. I understand this is a very custom user case, but can you guide me to a way of achieving this gracefully?

**Comment by jamuhl** [comment]
reading the docs you might find: https://www.i18next.com/translation-function/objects-and-arrays
