### ISSUE TITLE
Make the translation function fully type-safe

### ISSUE THREAD

**Issue by karol-majewski** [i18next/i18next#1504]
## 🚀 Feature Proposal

With the latest advancements in TypeScript, it's now possible to infer the correct paths from an object type. TypeScript 4.1 introduces [recursive conditional types](https://github.com/microsoft/TypeScript/pull/40002), and there is a [PR open](https://github.com/microsoft/TypeScript/pull/40336) that will enable string type concatenation on the type level.

## Motivation

`18next.t` accepts arbitrary strings. This allows silly human errors, since it's easy to make a typo.

## Example

I put together a [TypeScript Playground](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/MYewdgzgLgBFBOBDSAbRUCW4YF4YG8AoGGAIgAsQBbAU1IC4DiSzybEATDMAcwbIAqATwAONDjABSiAG6IAysHgYRsdDACCYITEWIUNAHSkANMxKkONCEpWZw-UsLGLlqmDQAeUGmA4QpWQVbdwAjHU4uXjhRa2NmAF8zCw4QYAh+IhYWCnYovkYnWNc7GAARNIBXWjAodCwwUkTCBMJCKFiYAAV0cgB5ADMAHgEPb19-GBBQgCsaYCgAPlwmEgBtAGkYbhgAaxohEAGYAQBdRgFN07GfPwDpuYWYAH4YTZMYQy+eqH7hy42p0W10YVxaa32h2OZwA3G0OmJdDRlPoMAAvcQ-P4jG4Te6zeZLFaSEDcIYAUW8SAWQyxgxGiw+0GUvDWQI+AHJDBzFnD2p0SWTRl5bpNmdweGyPmVcXcYOLeMscOYTrLJmyXjAORyYPQVcLxnK1pUwLswCAAO5ga6vAAGABJ8JcAAynBK23X6tUBY2m81Wj5fQzcAbImAAVRtMAdTrWroSjrKCfwgrAQ3D0sW7s92QVPD5VmAaHgNBgAxNCwaMCU7B8AhxIrxUwJC0WAAoEMgIGh7GALgBKRhtkS9Rh0-7LAA+SJRKHRmN69IEi37uGWeb5oEgsFgeBr6BoAg7SFQ9XA-b5AHoAFTX4jXk5sCCliCUSooCQWkDwXaGe+X9o2w5ShaEMNhOAlDkL0A4DqCMKwbDcXsoLhKAgNSdIwLySDoMAtZYNoDlOXA-IOVOaC0PwkCaCIrUEJCZDyNQtt8IwiBaOA7DeDI3CbzvGAHwEcgMACV8QHfCQkBE0tkA8eB4G-P8BIAtCCKMEjkRQmDqMMeitNUtisM4TTcMotSOI0+AeOYqi4I4vSmLwjk2IsvJNKYoA) illustrating the improved definition.

Once https://github.com/microsoft/TypeScript/pull/40336 is merged and released, the improved definition can be put in a separate file loaded only for the ones using the minimum required TypeScript version. In `package.json`, it should say:

```json
{
    "typesVersions": {
        ">=4.1.0-0": {
            "*": [
                /* Path to the new definition */
            ]
        }
    }
}
```

**Comment by rosskevin** [comment]
Very nice!  Once the new TS is released, we can accept a PR for this.  We may need to think about modifying our usage tests so that we can properly test it, we currently do not have any expect error notations being used.

**Comment by raynor85** [comment]
This should be reopened, it is a must have feature and we already have a solution for it.

**Comment by jamuhl** [comment]
stalebot

**Comment by akosbalogh** [comment]
up!?

**Comment by pierpo** [comment]
I started a PR to allow this. The full types work locally on my project your work + my PR, @karol-majewski 😊

**Comment by karol-majewski** [comment]
@pierpo I like your approach very much. It allows the consumers can decide whether they want things to stay as they are, or if they prefer full type safety for the price of slightly degraded performance. Also, it doesn't introduce much complexity to the core package.

Definitely worth considering!

**Comment by pedrodurek** [comment]
Hey guys, while we’re working on the documentation, I just want to clarify a few things about the types introduced on the react-i18next lib.

1 - For those who opt **not** to have the `t` function fully type-safe, it should work as before, so it shouldn’t have breaking changes and shouldn’t increase the **compilation time** (since it’ll fallback to the original types).
2 - For those who choose to have the `t` function fully type-safe, it’ll type not only the `keys`, but also the `return` type (that’s great when you’re using `returnObjects` set to true). 
3 - The **compilation time** only will increase according to the number of keys (since it’ll map all keys recursively). At SkipTheDishes, we have a few projects with more than 1500 keys, and it works smoothly. In our tests, we checked with more than 7k keys (you can check it here https://github.com/pedrodurek/i18n-type-tests).
4 - The types add to the core project (react-i18next) are a bit overwhelming indeed, but just because they aim to handle all features that the library supports, such as, single namespace, multiple namespaces, no namespaces, objects and arrays, fallback, template literal, `keys` and `return` typed, etc.
5 - The only setup needed in order to get the `t` function fully type-safe is the type augmentation, as we can see in this example: https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/no-namespaces/%40types/react-i18next/index.d.ts
It seems to be a complex setup, but it isn’t, and that’s the only way available by Typescript. Other libraries use the same approach (styled-components https://styled-components.com/docs/api#create-a-declarations-file), and it’ll become even more common as Typescript become more powerful.

Sorry for those who get affected with the bugs introduced in the first versions of v11.8.x. For now, we managed to solve all issues reported by users who choose not to use this feature (so it doesn’t look like a breaking change). And we’ll answer and address all issues reported for those who are interested. 

We’re working hard to bring a great experience to developers. This feature not only helps developers (with autocomplete and type check), but also prevent clients from complaining about string like this `dashboard.title` on the webpage/mobile app (that happens with us more than once), particularly when we’re maintaining a project and ended forgetting to update a key.

**Comment by jamuhl** [comment]
@karol-majewski sorry for missing this issue so long...currently I have no clear view if this can be closed with the last comment of @pedrodurek or if we're still waiting for some PR?

**Comment by pedrodurek** [comment]
Hey @jamuhl, If people are interested, I can move types from `react-i18next` to here, so we can also rely on the algorithm that infers keys and return types for the `i18n` t function as well. The only problem would be the breaking changes.

**Comment by jamuhl** [comment]
@adrai guess this would be worth a breaking release for typescript users and improve the experience using i18next

**Comment by adrai** [comment]
So the opposite of what I tried to describe here: https://github.com/i18next/react-i18next/issues/1361#issuecomment-908905362 ?
So this means also if using react-i18next or any other i18next plugin, tge appropriate i18next version needs to be installed...

So why not move all types completely out to a single i18next-types module? (it was like that in the beginning)

**Comment by jamuhl** [comment]
fully typesafe translations belongs to both i18next as is and react-i18next - so having them here sounds right to me.

Moving types out of the project does lead to even worse DX - I guess

**Comment by adrai** [comment]
ok, then we need to live with the fact, each time some react-i18next specific type is changing, i18next needs to be updated...

**Comment by pedrodurek** [comment]
Yeah, the best approach would be to move all types to here, so both libraries can leverage the type-safe feature. Alternatively, we can move all types to https://github.com/DefinitelyTyped/DefinitelyTyped, but it'd be hard to keep it updated, built-in types are always preferable.

**Comment by adrai** [comment]
Ok, let's try to move them to here

**Comment by pedrodurek** [comment]
Great, I'll be focusing on that in the coming days/weeks, I'll be also testing compilation time performance, so it may some time.

**Comment by davloperez** [comment]
How is this going @pedrodurek ? I think this feature is really cool and expected :)

**Comment by pedrodurek** [comment]
Hey @davloperez, I expect to have something in place by the end of this month/beginning of February

**Comment by OliverJAsh** [comment]
As far as I can see, the change proposed here wouldn't achieve _full_ type safety because it would still be possible to pass incorrect parameters. Example:

```json
{
    "intlNumber": "Some {{val, number}}"
}
```

```ts
i18next.t('intlNumber', { val: {} });
```

This should error at build time because we're passing an object to an argument (`val`) that expects `number`. At runtime the user will see the string `Some NaN`.

FormatJS/`react-intl` [has the same issue](https://github.com/formatjs/formatjs/issues/3346).

**Comment by jamuhl** [comment]
@OliverJAsh what you're asking is impossible to achieve - translations might come from backend, further those translations are plain strings and can't be handled by typescript, either because it's just a string or not even available during coding...

only option I would see is changing from string based translations to hardcoded template strings in a JS file for development...

but might be I'm missing something or someone has a super clever idea...

**Comment by OliverJAsh** [comment]
That's certainly the case if it's coming from a backend, but in many cases the strings are defined statically in the code, so this isn't a necessary limitation. In that case, there are a few ways we can extract type information for parameters:

- We can convert them to TypeScript functions with types for parameters. See [Vocab](https://github.com/seek-oss/vocab) for example.
- We can use a DSL such as JSX to define the messages and extract them to strings automatically. See [Lingui](https://lingui.js.org/) for example. Also [see this experiment](https://github.com/OliverJAsh/ts-icu-messageformat/blob/046e3d75473890df7701c9ffb3d38146bdb08c05/src/main.ts#L33) I created which provides a DSL for creating the ICU Message AST and then extracting types from this.

**Comment by jamuhl** [comment]
@OliverJAsh Feel free....as long it's optional and only affects typescript users I got nothing against it...just not something I can help with as I don't use typescript and won't ever use it.

**Comment by pedrodurek** [comment]
Hey @OliverJAsh, right now, typescript doesn't support getting literal values from JSON files yet [microsoft/TypeScript#32063](https://github.com/microsoft/TypeScript/issues/32063)

**Comment by tkow** [comment]
I recently came up with fully inference solution of t's function type in Typescript version >= 4.1.

<img width="879" alt="スクリーンショット 2022-02-06 16 30 34" src="https://user-images.githubusercontent.com/7004725/152672222-3767459b-3185-4ca1-9c4a-9f516cf3c8c5.png">

<img width="820" alt="スクリーンショット 2022-02-06 16 54 04" src="https://user-images.githubusercontent.com/7004725/152672236-2f0825fd-80be-4d81-8918-670284e62b14.png">

This type definition is followed by typescript playground.

In short, we can infer all arguments from typed dictionary object by as const and it can specify useTranslation and, if necessary earlier initialization its type by declare modules or wrap useTranslation function using my example's defined types like

```typescript
const useAppTranslation = () => {
  return useTranslation<TranslateKeys, TranslateOptions[TranslateKeys], TranslateTemplate[TranslateKeys]>()
}
```

What do you think adding this implements to your library?

https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAsghgZ2HAxgCwgHgAoBtUQASA9rgCYQBOUEAHsBAHZkJRKUCWjA5gHxQBeKAAMAJAG92XbgF9x4iXgIlyVGeolSeM4QChQkKNmJJ4SVBhwngAMQ60a9JizbBOPfkONI7Dug2ZWMUk3aTkFEPdZDXEuADMqIx0oAH4jKAAuVyj9cGgAFU4AWwAZCDjgACFKAkwSxwCXLT5BKHr-ZyCI+MT85LTCjlLyqpqULHzeLJLcwyVxlQpKTABBBs7s6U8oKDWOwNhEZHQsHupK-jSoQeGK6tqLqAAfI3wF0iWrUyOLLBXefhZRgQABuVF0s2gAFF6GNgIU4IwEPgGAB5MDADjERiYfIQIpgFHQfZNUIeVoAJQgKGIlDIODeRA+VFx+MJcAYvAANFBESBeBCaUjgFAyBwUK1xLodjs0MRuBAsgByBhIeTs8Zy1SUdRQVXAJVc6UyhDU7FkZX69WMrVLXXyU1CsjqfWG407MgAVzAlogavEXrA9oD3pdfoNRplUCVcDIYsx2LguHEMiVvv94g1EFtanUbqjcWIxCyUqjUYARnBKOmRfJgUhda7I2WdgAvEvulsyuUKmtKztRmSdocyXmsIVICEGaAAVUYWMY+WIAElGAxKI6EziZ55jQAKGfrA581JQPcAayyM4AlIJ+CDiBwyJkoMCwZRbyTWHuL1kzlBl1vAR70fMhbzSZcXzfKgAG4IV0CgUHwShoGnKAAGFiAJVBgEwAARbZSxlABtc8IBAKAuCgMiQGIOIoDwgBdLI8NI8jGN0IdIWuNkiXgMB8PFI8XCpGk6UwPkeT5AFWkw7CUFwucFyXVd103BccA5NAECXABlMluBhNwcMElAeWIxiAQFNC8QJIkVkobgEH40zhNYUTaXpSTeUYfkeRWXAOEQVpbPZBgXLw8UZKEcQ2IoqiaLo3ZAsQZjkqChA4sYtzNh4U8jLhBEkSJdEt1WFLMpoyyoNBRIuLQ7AtJ04h9KiAqTPyHkAC0cuaCztnyHKPPE7zpNPcQoE7YiAGlKMYKB2oUzBEvoqkimIMFVwoWhcW5XK+GyrJGuAbS9IMxbcLWjaIC2uhcRmyzzIAOherqeWmyzOOIi7lvIpKrs25g7smHlml4Q6dgmqA4rmqAAClHxxN7oyepVwayQb6rya4amKjkIFCokQt4-GXOnJKxRQazsaK5F8dKhdWCEQn8YcpyybyCmou42miWm8imYY4hgGOtBMHJ+jKYFXQJxFMAqzgIoEAx3G6bRDFGeIpUewgJVspizssxzato37Lidhs1WUQXBnsQQXF0M9JAsNtpEcuIcsACtqRFIQPe9hSBqtjkbY1u3KkQaAADJO3yR3naKV3WCjqAJrirJmjSk9zbm9c4gIHHETV0OtwQCPTVTzsAHoACoa4HGuGPKOBPVwEUQSTT1UOIKAUOAT1KHmjh6LgPVg63KAAHdgsYYWoELT1mAbqvOwofPW+AAA1TuIBSLI+WruuG4w4hF-bneoCdiBn0LahCQHpMEGXzsaTPvfX09Ipy3BKNa-rstG4zlNDfWkUAhQMHoN+CA3AnpQCKEmCAAAdBI8DcAQGvM-KM4D-DvwPr-I+ACoCoi9j7KeHATpQA7hueeoCuDrjAKQEO2IoAAFooCgLAJ6EUJ18Sig4ChBSuB4rzWIGHJEmCZQoSzLg3yh9-5Rkbqid8nAKBQHwDwT0cAFR6h7lfCROxcA8Hfs0ORx8lFUBUdAdR3BNEKlYMAXRpp9FqJ4AgYxBkLKmMIeYygli1GIhsVo7uaiiznm9NRcilF6KzxFAvZgbAIDQHzrgXAlYUDnlYLfUUEBkAcFwE-ABK8CxJlSagc8JQjH71kfg+RMpFHKKfNARgis-Ty3GN+Zo7DqBVhqCADBhTOxIncVEZ4+1PE1LMQ01R6Aqw6ISfLGoDAIkgAKQoopMoaK6QgAsjktJhnSC8QoohUzoAzOoA4tghJyGvhaQgNpSTKBYWWc4pEWydkOMoPsnghy6m7BQO0hA0gfLsJIQpV8c9R7GTxhPTpe4UCIigN-BJIpuC4A9iUiiDjiD9LWZ2PuA9GDEIDsANxWRyxFjQYiH5OxG7oTQFWHk0DYFKkQYwJUep6Uih6XAFZZCUmIugJ7RG19EUUThQipFpoUVosrCkzFRYcV1PWTsIVXAHK9NJftalUBG6tSBaA7lFEkoMKQNgR5ALaT2J7nAMAhIKKmmgHQqgHdcBQHvjUfJY5eRsEVoSCAziTUi3NX6TVnSXh9Q4hM7xJzc5UAYdbZhojS7OKdZQeNTDGAyJAMaLiqb87jCgAAdXIWgfIREdh-2PngCAkcoD0rBN6tFxBzy8m4RgMeRcE3zTiIvBSjM1EcDIrGtNjCtw8lvvA4AmI8qImfO6x+NDqDrRQtk3JnrmFOyBeQp6zjcL5H5ryr8+1WjNB5PkbeuAu6sCPf7UhftQXADPVSBAG9WhjQvORDGB7WAvH3QLCyPIk2M3frzDNSdcQXqvbwW8GNn0bzglxKhlEACMAAOYE9AsjFpOoNF4jBW6uqEPhlJcFdB5oLgAOQgJPbDpby1QErYQ6ttb63QFHk2ltHIOWoXHgueevbS4DqHam9NY7F2TundwHyc7L0esyaA5d0AKBrtYBuwFeVt27txN+3qBkT0GTPZBv07sH2tFvQpJ9fpX1CHfTRL9AtRl-pWQB9hYjNWga3OB89O8EDQZfPkODbcEOCjtiKK+Hm+NCG0w5o9nShCnuuEZ69TgDjmd9iC4llmX1tzfb5fge4gL8Ho-iwelcux6iyD+QrqcZC3mCieYKH6QD2d5b+79LmgN2xA7x7EXmkt+bvNcQLwBhycRC8KVOeooCjiEOFnrOIPMQG-We8eEAk7EUW9+xiK3O34xZgwDbq2tu8AK1OPc2t5S6x5JmG0zITZKiVLV-Q53YzxgXEmFMhpJs62VI9jBCFqTIVQtjAKaLJ7XzNaIqgoBMCoh5NgcUZFqBHpWkQ1oqPUTbAR+kzAVIACOnp+HX0wGnGisMMdpTJzIPa2OkfSzQgDG6QMdqTElFNKAs0Ep-XooNYKYaP78peIvNeXARU5VmmkaC1AgSf2-sjlLLgJevlqtLjnUAIb5AemN7i8AQDf12iFUZxHXVC6BnEUXZAISISB3qbGVIsxGaJT7XEPJ7eMnyNjeLBlCLs85-NVHjVKCYiTLj-E11bos4BBDfHhOUL0kZxH3avAHo5V1-r9VPLMD-gpDJFIA4ZQUhyocPXWBhpeV8lJPLlwjBVmD7gUPDud5O6Wgn5nuO9pu4IB7yAMksid-GN36AGR887E1x9VPPL9dl4khXny-Jq+B7rw3xkjuH2h-WoDba90Pod+2e7vIveoD94JnkbXDUmpnSiJDsA9tBqxb0y8afklpIDV0yMtIFkXz0ZmrDH6qPW9b4gz7TozQzTQ8gvRPSizNR6o8DX634PTgxfR-7c5H5h6b7Ax7RgyMSkbn4nTQEGRwE2Au5QA9T35RD9SG5HpP6z5jRpDf5+4LSwgmT-5oFM6AGYHe5pRQGX7SCEHr7h5t5j6PTQwQHIw76cQvgIxcCYDIxKioz07YxSELZv7SAuZ4QqHkgCCxw5Sf6S4q6ZDaFHrET-g2DZRpA2AGFRh34K6sDGGMAJDUA2DgEvTZ5mGdgWFkFAp55RjBA2AyASB4T+HiBKGYA-QUigweLCEETJBAj6EZwGSkbW5VjA6GB4TCyiyw5DRmgjQV7SQ8hKEwFSaeF5RCByFoytAhHcEtQEGPI378HoE7SY57QFHe5W6A7JG26pHpFaTN57rdQaHcCf5CAUHMxZFiTl4gCV78jjRTQMHIG0SrSsGJ5AFYEYwp5HoZ4gBZ72GJA55G4EajLC7lAW6nhVGFF8HhEiGvTvTVRHQX7VFX61EIBEFCHPTXEc6fSjhZAhGyHyFtFIQdFoRpEiw9EPo2AogBDfoyE5TAmiy9Ez6TFz7RQ7CkE2GoHjEIk8j-gESnjqHFFSZpDqEsTdEnS9HgkciQkCwyFxRJRdSWSxHvi6BAA

**Comment by justin-barca-at-camis** [comment]
I decided to have all my translations in TS so that I could make them type-safe. I devised this little TS scheme to ensure that all translations for all languages and all namespaces are defined. 

```ts
export enum TRANSLATION_KEYS {
  LOGIN,
}

enum LANGUAGE {
  EN = 'en',
}

enum TRANSLATION_NAMESPACES {
  DEFAULT = 'translation',
}

type Translation = {
  [K in TRANSLATION_KEYS]: string;
};

type TranslationResources = {
  [L in LANGUAGE]: TranslationNamespaces;
};

type TranslationNamespaces = {
  [N in TRANSLATION_NAMESPACES]: Translation
};

export const resources: TranslationResources = {
  [LANGUAGE.EN]: {
    [TRANSLATION_NAMESPACES.DEFAULT]: {
      [TRANSLATION_KEYS.LOGIN]: 'Login',

    },
  },
};
```

However, this doesn't work properly because the enum values are numbers. It will work if you manually assign a string to each of the `TRANSLATION_KEYS` and I'd really like to avoid this. Is there any way that this library could also support numbers as translation keys?

I've thought of ways around this with utility functions. You can re-map the keys of each translation set to be strings (or just be careful and string-interpolate all them) and then create a custom t function that would take the numeric keys and cast them to string.

```ts
export const useCustomTranslation = () => {
  const useTransOriginal = useTranslation();
  useTransOriginal.t('a');
  const numFriendlyT = (keyOrKeys: TRANSLATION_KEYS | TRANSLATION_KEYS[], options?: TOptions | string) => {
    if (Array.isArray(keyOrKeys)) {
      return useTransOriginal.t(keyOrKeys.map(key => `${key}`), options);
    }
    return useTransOriginal.t(`${keyOrKeys}`, options);
  };
  return { ...useTransOriginal, t: numFriendlyT };
};
```

Thoughts?

**Comment by OliverJAsh** [comment]
> As far as I can see, the change proposed here wouldn't achieve _full_ type safety because it would still be possible to pass incorrect parameters.

If anyone is interested, this is how we solved this problem and achieved _full_ type safety for our translated messages: https://twitter.com/OliverJAsh/status/1521505324791967744

**Comment by adrai** [comment]
> > As far as I can see, the change proposed here wouldn't achieve _full_ type safety because it would still be possible to pass incorrect parameters.
> 
> 
> 
> If anyone is interested, this is how we solved this problem and achieved _full_ type safety for our translated messages: https://twitter.com/OliverJAsh/status/1521505324791967744

@pedrodurek this sounds interesting, isn't it? but probably not easy applicable to i18next, right? What's your opinion?

**Comment by ashkan-pm** [comment]
Any idea when this feature is going to be added?

**Comment by pedrodurek** [comment]
The migration is almost done, I believe I'll have a PR opened by the end of the next week

**Comment by gallaouim** [comment]
is this Feature already in Production ?

**Comment by JohnHallstrom** [comment]
> is this Feature already in Production ?

I think we're still patiently awaiting its linked pull request getting finished and merged:
- https://github.com/i18next/i18next/pull/1775
