### ISSUE TITLE
Can Formatting be done in a Nested translation?

### ISSUE THREAD

**Issue by lautarodragan** [i18next/i18next#1517]
I'd like to use nested translations with formatting, so I can pick up a different key and capitalize it when needed.

I don't know whether this is possible right now. The documentation doesn't mention it, and I haven't been able to achieve it by trying different syntax combinations. 

There is a good question on SO about this: https://stackoverflow.com/questions/38867564/how-to-apply-a-formatter-in-nested-translations-with-i18next, but it doesn't have an answer.

**Comment by adrai** [comment]
Can you please create an executable example showing that this is not working?

Here you have one that works: https://jsfiddle.net/vge5rh1L/2/

**Comment by lautarodragan** [comment]
Hey @adrai, thanks for creating that jsfiddle!

That does indeed work well. But I mean _nested_ as mentioned in the [nesting docs](https://www.i18next.com/translation-function/nesting), as in `$t()`.

Basically I want one key to dynamically load a different key and apply a transformation to it.

I can't recall right now, but I did achieve the one key dynamically loading and interpolating a different key by passing the second's key name as an argument. It was something like

```json
"message": "Will apply $t(cadence.{{keyName}}.adverb) cadence",
"cadence": {
  "monthly": {
    "noun": "month",
    "adverb": "monthly"
  },
  "yearly": {
    "noun": "year",
    "adverb": "yearly"
  },
}
```

Which I used from code by calling `t('message', cadence === Cadence.Monthly ? 'monthly' : 'yearly')`, roughly speaking.

This DID work, but then I wanted to apply a transform to it and couldn't figure out _how_.

**Comment by adrai** [comment]
https://jsfiddle.net/hea40rv8/ ?

**Comment by lautarodragan** [comment]
Thanks again @adrai!

That, too, works. But is there a way to apply formatting at the calling place?

Something like

```
"message": "Will apply $t(cadence.{{keyName}}.adverb, uppercase) cadence",
```

The issue I had in particular is that some keys will need to interpolate `cadence.{{keyName}}.adverb` at the beginning, so they'll need to be capitalized, while other keys (or languages) may need it later in the sentence. Although I did solve it with CSS (`::first-letter { text-transform: uppercase; }`), so it's more of a curiosity thing right now (can't think of other cases in which I'd need to apply a transform to the whole nested key).

**Comment by FRSgit** [comment]
@lautarodragan :+1: from me!
In my case I have a `postprocessor` which - in an environment setup for translators - adds prefix & suffix to the every key, so another tool can pick it up later on (e.g. `some_key` becomes `{{__phrase_some_key__}}`).
Unfortunately, there is no way to make this working with the nested keys. In the end I couldn't use nesting feature at all - I had to create my own `t` function wrapper which runs original `t` function for every nested key in the string.

IMO the current implementation of a nesting feature is a bit counterintuitive and it would be great if nested keys could follow the same translation process/plugin pipeline as unnested ones.

@adrai Do you know why this feature was implemented in this way in the first place? Is there something important I'm missing?

**Comment by adrai** [comment]
> Do you know why this feature was implemented in this way in the first place? Is there something important I'm missing?

@FRSgit No, I don't know why, maybe @jamuhl?

Personally, I'm not a big fan of the nesting feature in general, because it's not really good for the translator's workflow.
But, hey... this is open source, if you like nesting to be more "complete" (and the code more complex), feel free to submit a PR.

**Comment by jamuhl** [comment]
postProcessor is the final step before returning the found translation: https://github.com/i18next/i18next/blob/master/src/Translator.js#L334

it's not a step that runs during interpolation and nesting

**Comment by FRSgit** [comment]
@jamuhl I understand that, the question is - would there be possibility to add a step which runs for nested translations

Or maybe nested translations could be run through exactly the same pipeline as the "regular translations"?

**Comment by jamuhl** [comment]
chicken egg issue...you nest interpolation that nests nestings with interpolation...

do yourself a favor and keep translations as simple as possible...

**Comment by FRSgit** [comment]
Chicken or the egg dilemma... or a case for a recursion.
I think that in the current state the nesting feature is pretty much unusable. The translations can hardly be nested/reused, because the `i18next` handles them in completely different fashion than the regular ones.

If that's the final decision regarding this topic I would propose the docs should mention that the `i18next` creates a **separate, absolutely different working pipeline** for the nested translations which is **incompatible with the rest of the library**.

The main problem still is that `i18next` doesn't provide any preprocessing possibilities, so there is no way of creating plugin which would cover this case without hacking the internals of library (which I needed to do in my env). Would that be something worth considering?

**Comment by adrai** [comment]
> But, hey... this is open source, if you like nesting to be more "complete" (and the code more complex), feel free to submit a PR.

**Comment by FRSgit** [comment]
@adrai I agree! That's why I asked which scenario would you see me/us follow in the PR:
> the question is - would there be possibility to add a step which runs for nested translations
> Or maybe nested translations could be run through exactly the same pipeline as the "regular translations"?

I wanted to discuss this with library's maintainers, because in the end it's your decision to make (and PR to approve/merge).

Unfortunately, instead I've got some random comment (personal attack?) which've added nothing to the conversation :<

So, my questions are still open. I believe I shouldn't start working on a PR without having your opinion on that guys 🤔

**Comment by FRSgit** [comment]
Also, closing a PR with no explanation feels like a big "no" regarding the functionality - that's why I've proposed an other solution to the problem (adding the preprocessors to the translation pipeline & moving nesting feature into a plugin).

**Comment by adrai** [comment]
In my "personal" opinion: if you achieve an internal refactoring without breaking the existing interface and the existing functionality by having a less complex code, this would be awesome.
I would not add an additional "plugins" possibility right now... this is for sure a topic for a major "redesign" of i18next... btw: I've already tried some cool hookable approach myself for a possible "redesigned" i18next...

**Comment by FRSgit** [comment]
@adrai I agree that's not the best for the translator's workflow. But still, there are cases when nesting translations makes sense. There are tools out there which make use of this kind of "translation referencing" and make it a pretty snappy experience for the user (translator).
But it's not the most important case, that's why I've proposed adding it as a plugin.
You've mentioned some "cool hookable approach" you've tried yourself - can you show me/ tell me something more about it?

So - do I get a green light for making nested translations follow the same pipeline as the regular ones? Is that a change that you think could be merged into the existing codebase (ofc if it won't overcomplicate it too much)?

**Comment by adrai** [comment]
Of course... try it 😉

btw: this was my experiment: https://github.com/adrai/i18next-next#some-differences

**Comment by jamuhl** [comment]
@FRSgit didn't mean to "personal attack" you...sorry if it sounded like that.

the case @lautarodragan describes - at least in my tests already work:

- https://jsfiddle.net/k1ajb4xo/8/
- https://github.com/i18next/i18next/blob/master/test/i18next.translation.formatting.spec.js#L13
- related PR: https://github.com/i18next/i18next/pull/1419

So, we could already have something like `"nested: $t(k.{{keyName}}, uppercase) works"` called like `i18next.t('nest', { keyName: 'form'})`

**Comment by Arkellys** [comment]
Using `"nested: $t(k.{{keyName}}, uppercase)"` doesn't seem to work anymore with v21.0.0

**Comment by adrai** [comment]
> Using `"nested: $t(k.{{keyName}}, uppercase)"` doesn't seem to work anymore with v21.0.0

@Arkellys create a reproducible example and open a new issue please.

**Comment by Arkellys** [comment]
It looks like I made a mistake in my code because as your example shows, it works perfectly fine. Thanks!
