### ISSUE TITLE
i18next Problem 

### ISSUE THREAD

**Issue by Neba2262** [i18next/i18next#1663]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Windown 10
- *any other relevant information*

**Comment by adrai** [comment]
issue template not correctly filled

**Comment by Neba2262** [comment]
which template?

**Comment by jamuhl** [comment]
🐛 Bug Report
A clear and concise description of what the bug is.

To Reproduce
A codesandbox example or similar
or at least steps to reproduce the behavior:

// Paste your code here
Expected behavior
A clear and concise description of what you expected to happen.

// Paste the expected results here
Your Environment
runtime version: i.e. node v14, deno, browser xy
i18next version: i.e. 19.5.3
os: Windown 10
any other relevant information

that template

we need more than: "DOES NOT WORK"
