### ISSUE TITLE
Missing plural keys in translation

### ISSUE THREAD

**Issue by MaksUr** [i18next/i18next#1690]
https://www.i18next.com/principles/fallback#key-not-found

It's not said what will happen with plural items. Typical plural form looks like `t('Found {{count}} files', {count: foundFilesCount})`.
If translation is missing for the key, i18next will return `'Found 1 files'` which is WRONG. In `gettext` system, plural function ngettext REQUIRES to specify both forms for English in source file, so on missing translation it can choose correct form of the phrase for English. This functionality is missing here. I consider it a bug. And also this case description is missing in the documentation (see link I have provided at beginning).

**Comment by MaksUr** [comment]
@socketpair

**Comment by jamuhl** [comment]
@MaksUr i18next is not gettext based...missing translations are handled as good as possible - but still missing are a fallback not a "you're doing it right"

beside that - gettext has no fallback to key -> it always has resource files

using text as keys is also not the primary way to use i18next: `t('section.filesCount', {count: foundFilesCount})`

=> why using plain keys is better instead of natural language -> it's easier to fix or change texts in source language
