### ISSUE TITLE
Version 21.6.4 breaks interpolation

### ISSUE THREAD

**Issue by mrlubos** [i18next/i18next#1721]
## 🐛 Bug Report

Since version 21.6.4, translations with undefined variables print unescaped strings from the translations file. This behaviour was not observed in version 21.6.3 and hasn't been fixed since 21.6.4.

## To Reproduce

See [CodeSandbox](https://codesandbox.io/s/react-i18next-forked-h8uc4?file=/src/app.js:0-48). Change `i18next` version to `21.6.3` and observe the string `{{ foo }}` disappears which is the correct behaviour.

## Expected behavior

The translation string is not printed, i.e. we print an empty string

## Your Environment

- *i18next version*: i.e. 21.6.4
- *os*: Mac

**Comment by adrai** [comment]
Yes, this is expected, since `skipOnVariables` is true by default for v21.0.0 => https://www.i18next.com/misc/migration-guide#skiponvariables-true

If you still wish the old behaviour, you need to pass `skipOnVariables: false` like this: https://codesandbox.io/s/react-i18next-forked-cifxl?file=/src/i18n.js:345-367

**Comment by mrlubos** [comment]
Thanks @adrai! Although you can see this behaviour has been working as expected until 21.6.4, any prior 21.x.x release didn't break it

**Comment by adrai** [comment]
Yes, this was an error on previous versions

**Comment by adrai** [comment]
tldr; since v21.0.0 this was an error, and it was fixed in v21.6.4

**Comment by bratzie** [comment]
@adrai I recently ran into this issue as well. It feels to me like the intuitive behaviour is to hide the interpolation marker, i.e. `{{interpolate}}`, if you do not send in the value, or send in `undefined` explicitly. You can still get similar results if you explicitly send `null` as the variable, but not `undefined` or leaving it out completely.

I'm guessing the change was done due to security implications, but would there be any possibility to still hide the variables if they are not sent to the t function with `skipOnVariables: true`? Is there any documentation as to what security exploit this prevented? :o

**Comment by adrai** [comment]
Because of these:
=> https://github.com/i18next/i18next/issues/1490
https://github.com/i18next/i18next/issues/1479

{{ variable }} is kept, because it may be you want to have this in the translated text...

The only thing I could think of is changing the interpolation if an undefined value is explicitly passed, so something like this:


```js
// resourceKey: "welcome": "{{ foo }}",

console.log(i18next.t('welcome', { foo: 'hi' })) // logs: "hi"
console.log(i18next.t('welcome', { foo: '' })) // logs: ""
console.log(i18next.t('welcome', { foo: null })) // logs: ""
console.log(i18next.t('welcome', { foo: undefined })) // logs: "" <= we could enable this instead of "{{ foo }}"
console.log(i18next.t('welcome', {})) // logs: "{{ foo }}" <= but this will stay like that
```

**Comment by adrai** [comment]
> This is what I would expect with the defaults in the latest 21.X.X version. (see sandbox [here](https://codesandbox.io/s/react-i18next-forked-j817j?file=/src/i18n.js) to observe passing `undefined` not working as you describe).

You're not using v21.6.8 in the sandbox yet.

**Comment by bratzie** [comment]
Yeah, good point! Then the only thing that should still be odd (to me) would be the 5'th log where I would expect this behavior to make it work like it used to with `skipOnVariables: false` and pre version 21.

```js
console.log(i18next.t('welcome', {})) // logs: "" => currently displays "{{ foo }}" as of 21.6.8
console.log(i18next.t('welcome')) // logs: "" => currently displays "{{ foo }}" as of 21.6.8
```

Or am I going crazy? :D

**Comment by adrai** [comment]
No, this will not change, I'm sorry.

**Comment by bratzie** [comment]
Ok! Fair enough, if it is intended behavior then I'll work around it.

The fix with undefined really helped though! Thank you for that quick fix :)

**Comment by adrai** [comment]
Yep, $t() usage was missing. v21.6.9 is better ;-)
