### ISSUE TITLE
Add some form of Lazy TFunction

### ISSUE THREAD

**Issue by jon-zu** [i18next/i18next#1731]
## 🚀 Feature Proposal

I would propose that we add a lazy TFunction, which supports defining translated string prior to initialization of i18next. 'lazyt' might be a bad name, maybe someone has a better idea.

## Motivation

The main motivation is that  libraries exists which can parse the ts/js AST and auto-generate the translation files. However, those usually look for a TFunction-call which doesn't play nicely If you define global objects in your code, because It requirs actual computation to deduce this: ```t(globalObject.label)```. If we used the translated string directely in the global object, this would result in TFunction-calls prior to initialization. 

## Example

```typescript
export type LazyT<TResult extends TFunctionResult = string> = (t: TFunction) => TResult;


  export function lazyt<
  TResult extends TFunctionResult = string,
  TKeys extends TFunctionKeys = string,
  TInterpolationMap extends object = StringMap,
>(key: TKeys | TKeys[], options?: TOptions<TInterpolationMap> | string): LazyT<TResult>{
  return (t: TFunction) => t(key, options);
}

const objWithLabel = {
   label: lazyt('First Item')
}

// Usage:
objWithLabel.label(i18next.t)
```

**Comment by JonasZ95** [comment]
Regarding option a, this depends on the load order and when init is called, but in case you have a global variable like this you cannot really wait for init. So a lazy-like function would be an actual solution for this problem because It would allow you to do this with well-defined behavior.

**Comment by adrai** [comment]
Calling the t function without checking if i18next has been initialized (i18next.isInitialized) or the namespace got loaded, needs you to handle that in some way...

so a lazyT function would only work, if it would be asynchronous.... so you would have to call `await lazyT()` because the translations could not be loaded yet... etc...

If you know of a better solution, feel free to provide a PR

**Comment by jamuhl** [comment]
A use case where this is needed would help.

Right now this looks to me like adding something useless as you assume to call lazyt when i18next is initialized...in that case you only wrap t for nothing...as calling t first place would do the same.

But possible I don't understand what you mean with "The main motivation is that libraries exists which can parse the ts/js AST and auto-generate the translation files." as I only know tools like i18next-parser and i18next-scanner - which work on the regular t function already

**Comment by JonasZ95** [comment]
@jamuhl 

Firstly, sorry for the late reply as I was busy with my exams. My main use case is that I have configuration-like objects defined in ts files. For example, something like this:

auth-providers.ts
```
export const authProvider1 = {
   id: '1',
   name: lazyt('AuthProvider1'),
   description: lazyt('For Mails ending with xy.com')
}


export const authProvider2 = {
   id: '2',
   name: lazyt('AuthProvider2'),
   description: lazyt('For Mails ending with yz.com')
}
```

I don't think I can call ```t``` here for 2 reasons:
1. i18next might not be initialized yet
2. In case the backend loads another translation configuration, the name and description won't be updated

> But possible I don't understand what you mean with "The main motivation is that libraries exists which can parse the ts/js AST and auto-generate the translation files." as I only know tools like i18next-parser and i18next-scanner - which work on the regular t function already

I'm using i18next-parser, which can be configured to look for additional function names  as well(in my case I added lazy). The problem is those tools will have problems to evaluate this: ```t(authProvider2.name)```, instead of evaluating those libraries look for a const string literal passed to as first parameter to the t function.

So reiterating the discussion so far I think I should make 2 things more clear:
1. Yes, It's mostly a gimmick for typescript users to have your translated strings somewhat correctly types
2. My main motivation is to improve the support for described scenario in typescript

**Comment by jamuhl** [comment]
But then you easily can define some function yourself...

`const lazyt = (key) => { return function () { return t(key) } }`

**Comment by JonasZ95** [comment]
Not really, because t has more than 1 parameter.

**Comment by JonasZ95** [comment]
Well, I thought this was not necessary as the t function already has a defined type signature, my primary use case is string interpolation. I'm also not asking how I should solve this, as the first post already contains a solution to this. What I intended to discuss If It makes sense to add to the i18next because the type signature for lazyt should stay in sync with t. 

However, It seems the demand for this is basically non-existing.
