### ISSUE TITLE
Correct usage of returnObjects with TypeScript is not documented

### ISSUE THREAD

**Issue by Jiia** [i18next/i18next#2151]
When using TypeScript and passing `returnObjects: true` to the `t` function, you will find out that the the compiler thinks the return type is still a string.

Your resource might look like this:

```json
{
  "key": ["a", "b", "c"]
}
```

```javascript
t('key', { returnObjects: true }).map(v => v)
```

> Property 'map' does not exist on type 'DefaultTReturn<{ returnObjects: true; }>'. Property 'map' does not exist on type 'string'

Multiple issues on this forum and StackOverflow guide you to fix it by passing a type argument matching the resource. However, that doesn't work anymore either:

```typescript
t<string[]>('key', { returnObjects: true }).map(v => v)
```
> Expected 3 type arguments, but got 1.

I have crawled through Github, StackOverflow and Google and not found an explanation how to use the type arguments. The source code type definitions are so complicated and poorly named it's almost impossible to decipher what the correct arguments might be.

It would be highly appreciated if the correct usage would be added to the documentation:
- https://www.i18next.com/overview/typescript
- https://www.i18next.com/translation-function/objects-and-arrays

**Comment by adrai** [comment]
seems to work here: https://github.com/i18next/i18next/blob/master/test/typescript/array-access/t.test.ts#L41

**Comment by marcalexiei** [comment]
Are you using `CustomTypeOptions` https://www.i18next.com/overview/typescript#create-a-declaration-file)?
Could you please provide a minimal reproduction example?

----

> Multiple issues on this forum and StackOverflow guide you to fix it by passing a type argument matching the resource. 

That was working until v23 now types are more complicated. You can find out more in the migration guide:
https://www.i18next.com/misc/migration-guide#v22.x.x-to-v23.0.0

Now `TFunction` has different type parameters:

https://github.com/i18next/i18next/blob/4685beae6be252f74d5b1002f93e731b5f46220d/typescript/t.d.ts#L260-L263

- `Key` is the key (who would have guess? 😅)
- `TOpt` are the Options supplied to the function (`context`, `count`, ...)
- `Ret` is the return type (the one you need to customise)
- `ActualOptions` is used to provide key proper type check inside `t` options to be sure that all `{{values}}` in the key are provided (if the relevant key is a const value and not a simple string).

`Key`, `TOpt` nad `Ret` are required so that's why you are getting:

```text
Expected 3 type arguments, but got 1.
```

so to correctly type the response you should do something like this:

```ts
t<'key', {.returnObjects: true }, string[]>('key', { returnObjects: true }).map(v => v)
```

Anyway is just a guess, if you provide me a minimal reproduction example I might be able to provide a better solution

----

> The source code type definitions are so complicated and poorly named it's almost impossible to decipher what the correct arguments might be.

I hope that the previous explanation has made the type definitions more easy to understand 😉

----

> It would be highly appreciated if the correct usage would be added to the documentation

When I got time I'll see what I can do to improve the documentation.

**Comment by Jiia** [comment]
Thank you so much for the detailed and helpful answer! 🙏 

> Are you using CustomTypeOptions https://www.i18next.com/overview/typescript#create-a-declaration-file)?

No I'm not using that.

> Could you please provide a minimal reproduction example?

https://codesandbox.io/p/sandbox/modest-bash-rc7p2f?file=%2Fsrc%2Findex.ts%3A8%2C1

> I hope that the previous explanation has made the type definitions more easy to understand

They definitely did, thank you! The solution you provided is working perfectly. I tried to make it less verbose by making a reusable function with one generic type argument for the return type, but couldn't come up with constraints for the argument that would satisfy the compiler.  Ended up with something like this, which is not ideal or robust but works for the use case:

```typescript
import i18next, { TOptions } from 'i18next'

export const tArray = (key: string, options?: TOptions) =>
  i18next.t<string, { returnObjects: true } & TOptions, string[]>(key, {
    ...options,
    returnObjects: true,
  })
```

**Comment by marcalexiei** [comment]
As an alternative you can cast the return value of the `t` function:

When no `Resources` are defined inside `CustomTypeOptions` and `returnObject` options is set to `true`
`t` function  returns `$SpecialObject`:
https://github.com/i18next/i18next/blob/4685beae6be252f74d5b1002f93e731b5f46220d/typescript/helpers.d.ts#L5

As you can see it is a union of array of string or objects so you can use a casting to properly better define the return value.

### Example with object

```ts
const something = t('myTypeKey', { returnObjects: true }) as { title: string, text: string };
expectTypeOf(something).toEqualTypeOf<{ title: string; text: string }>();
```

### Example with array

```ts
const something = t('myTypeKey', { returnObjects: true }) as Array<string>;
expectTypeOf(something).toEqualTypeOf<Array<string>>();
```
