### ISSUE TITLE
Don't get the correct types if the key contains _

### ISSUE THREAD

**Issue by catalinbotean** [i18next/i18next#2177]
## 🐛 Bug Report

If I have keys that contain `_`, I will get suggestion of keys that don't exist. This works perfectly if the keys don't contain `_`

## To Reproduce

If I get this keys
```
{
  "NEW_PROJECT_TITLE": "New project title",
  "NEW_PROJECT_DESCRIPTION": "New project description",
  "NEW_PROJECT_SUBMIT": "Submit"
}
```

I get the following suggestions and no typescript error 
<img width="693" alt="Screenshot 2024-04-23 at 09 28 21" src="https://github.com/i18next/i18next/assets/62332851/b734fd29-483e-430a-a498-b1fba8c059de">

<img width="463" alt="Screenshot 2024-04-23 at 09 28 29" src="https://github.com/i18next/i18next/assets/62332851/8d783a7d-d399-4b10-9a26-4c61032e9ace">

It can be reproduced even in the i18next-typescript-examples repository, [https://github.com/locize/i18next-typescript-examples/tree/main/1](https://github.com/locize/i18next-typescript-examples/tree/main/1)
## Expected behavior
I expect to get typescript errors for the non-existing keys even if the keys contain `_`

## Your Environment

- "i18next": "23.11.2",
- *os*: Mac

**Comment by adrai** [comment]
That's because of the contextSeparator and the pluralSeparator

https://www.i18next.com/overview/configuration-options#others

https://www.i18next.com/overview/typescript#custom-type-options

if you use different separators, or don't use context or plural features, just change those options to a different character.
