### ISSUE TITLE
v23.11.5 breaks the useTranslation() hook with name-spaced translation files

### ISSUE THREAD

**Issue by nataliadavtyan** [i18next/i18next#2196]
## 🐛 Bug Report

After bumping the version, translations no longer work. v23.11.4 works just fine with the exact same code / setup.

## To Reproduce

Try to translate with a simple setup like below:

### Component
```js
export const Hero = () => {
  const { t } = useTranslation();

  return (
        <h1>
          {t("heroTitle")}
        </h1>
   )
}
```
### Config
```js
i18n
  .use(HttpBackend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init<HttpBackendOptions>({
    load: "languageOnly",
    fallbackLng: "en",
    debug: true,
    interpolation: {
      escapeValue: false
    },
    ns: ["common", "landing"],
    fallbackNS: ["common", "landing"],
    backend: {
      loadPath: `${currentHost}i18n/{{lng}}/{{ns}}.json`
    }
  });
```

### Translation
```js
// i18n/en/landing.json
{
    "heroTitle": "This is a test Hero section"
}
```

## Expected behavior

It should translate the same way as the previous minor version.

## Your Environment

- *i18next version*: v23.11.5 (works perfectly with v23.11.4)
- *i18next-browser-languagedetector*: 8.0.0
- *i18next-http-backend*: 2.5.2
- *react-i18next*: 14.1.1

**Comment by adrai** [comment]
Seems to work in the examples...
Can you create a minimal reproducible example repository please?

**Comment by adrai** [comment]
// @VIKTORVAV99

**Comment by VIKTORVAV99** [comment]
I don't see how the code changes in 23.11.5 would have caused that, they should be functionally identical and supported as far back as Node 0.10.

Is that the only dependency that got updated?

Here are all the code changes between the versions: https://github.com/i18next/i18next/compare/v23.11.4...v23.11.5

PS: Are there not already tests covering this?

**Comment by adrai** [comment]
this works: https://github.com/i18next/react-i18next/tree/master/example/react

**Comment by VIKTORVAV99** [comment]
I can't replicate this locally with the following config:
```ts
i18n
  .use(resourcesToBackend((language: string, ns: string) => import(`../locales/${language}/${ns}.json`)))
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    detection: {
      order: ['querystring', 'localStorage', 'sessionStorage', 'navigator', 'htmlTag'],
      lookupQuerystring: 'lang',
      caches: ['localStorage'],
    },
    interpolation: {
      escapeValue: false,
    },
    ns: ['core', 'faq'],
    fallbackNS: ['core', 'faq'],
  });
```
It works identically on both 23.11.4 and 23.11.5 as far as I can tell.

**Comment by Helen2hang** [comment]
I also got the error on my React-native project that uses i18next with `^23.11.4`, I also use `useTranslation` on my project. I ran the project today for the first time and now the translations does not work anymore. It worked last Thursday that I ran the project. Now I always get `i18next::translator: missingKey`

**Comment by adrai** [comment]
Please provide a minimal reproducible example repository or codesandbox.

**Comment by Helen2hang** [comment]
Sorry I found the issue in my project, the problem was still happening even when I switched to 23.11.4 so I don't think it's related to 23.11.5.
we recently added `ns: ["fr", "en"],` into our config for i18n and it broke it. After removing it, the translation works again.

```
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

import fr from "./assets/locales/fr/translation.json";
import en from "./assets/locales/en/translation.json";

const resources = {
  fr: {
    translation: fr,
  },
  en: {
    translation: en,
  },
};

const defaultLanguage = "en";

if (!i18n.isInitialized) {
  i18n.use(initReactI18next).init({
    compatibilityJSON: "v3",
    fallbackLng: defaultLanguage,
    debug: __DEV__,
    interpolation: {
      escapeValue: false,
    },
    ns: ["fr", "en"], <--- this broke
    resources,

    react: {
      useSuspense: true,
    },
  });
}
export default i18n;

```

**Comment by dmilla** [comment]
Hello everyone, I've ran into a similar issue while bumping dependencies and I hope I can bring some light into this issue. After spending some time replicating it in a [code sandbox ](https://codesandbox.io/p/devbox/vite-react-ts-forked-s5xdsm?file=%2Fsrc%2FApp.tsx%3A18%2C30&workspaceId=f9a7fb4a-5774-4b51-81a5-3c1c6d4bd589) here's my thoughts:

1. i18next works fine while used standalone - so it's probably not directly related to this last version
2. Adding a component library ("@web3auth/modal": "8.6.1") that also uses i18next at the same version, somehow it overrides the translations
3. Translations may have been working fine until bumping dependencies (and work when downgrading to 23.11.4) because maybe they were treated separately thus avoiding the conflict / override / whatever is happening

Maybe the issue is therefore not related to the version bump but to conflicting settings when using the external library? Here's the [i18n config file of the external component lib](https://github.com/Web3Auth/web3auth-web/blob/dbcd5dbfed638419321f2ae9807d8ff6967329ac/packages/ui/src/localeImport.ts#L3), in case it helps.

Specifically I'm seeing the library is calling `use(initReactI18next)` which was leading to a [similar issue](https://github.com/i18next/react-i18next/issues/1690), but it's still being used in the [react-component-lib example](https://github.com/i18next/react-i18next/blob/master/example/react-component-lib/src/i18n.js).

Could you please help us figure out what's causing the issue in the provided sandbox and what would be the correct way for setting this up? Thanks a lot!

**Comment by adrai** [comment]
> Hello everyone, I've ran into a similar issue while bumping dependencies and I hope I can bring some light into this issue. After spending some time replicating it in a [code sandbox ](https://codesandbox.io/p/devbox/vite-react-ts-forked-s5xdsm?file=%2Fsrc%2FApp.tsx%3A18%2C30&workspaceId=f9a7fb4a-5774-4b51-81a5-3c1c6d4bd589) here's my thoughts:
> 
> 1. i18next works fine while used standalone - so it's probably not directly related to this last version
> 2. Adding a component library ("@web3auth/modal": "8.6.1") that also uses i18next at the same version, somehow it overrides the translations (logging the data from the i18n instance we see that only the library translations are available in the store)
> 3. Translations may have been working fine until bumping dependencies (and work when downgrading to 23.11.4) because maybe they were treated separately thus avoiding the conflict / override / whatever is happening
> 
> Maybe the issue is therefore not related to the version bump but to conflicting settings when using the external library? Here's the [i18n config file of the external component lib](https://github.com/Web3Auth/web3auth-web/blob/dbcd5dbfed638419321f2ae9807d8ff6967329ac/packages/ui/src/localeImport.ts#L3), in case it helps.
> 
> Specifically I'm seeing the library is calling `use(initReactI18next)` which was leading to a [similar issue](https://github.com/i18next/react-i18next/issues/1690), but it's still being used in the [react-component-lib example](https://github.com/i18next/react-i18next/blob/master/example/react-component-lib/src/i18n.js).
> 
> Could you please help us figure out what's causing the issue in the provided sandbox and what would be the correct way for setting this up? Thanks a lot!

I just updated the dependecies for our example: https://github.com/i18next/react-i18next/commit/9fd452dc23de13410726e9ae010325157d1c5fd1 and it seems to work as expected...
You may want to open an issue in their repository: https://github.com/Web3Auth/web3auth-web

**Comment by nataliadavtyan** [comment]
Thank you @adrai ! Let us explore a little more on where the issue comes from and we'll get back to you. Thank you again!

**Comment by nataliadavtyan** [comment]
Hi @adrai ! The code seems to work with the new updates! Thank you very much!

Closing the issue
