### ISSUE TITLE
Type broke in 23.12.1

### ISSUE THREAD

**Issue by hieuminh1810** [i18next/i18next#2214]
## 💥 Regression Report

I have seen keys that are not in the JSON file

![Screenshot 2024-07-15 at 3 31 36 PM](https://github.com/user-attachments/assets/347b5176-d6a5-48ec-93e7-7b2786845ca0)

## Last working version

Worked up to version: "i18next": "22.4.6",   "react-i18next": "12.1.1"

Stopped working in version:  "i18next": "^23.12.1",   "react-i18next": "^14.1.2"

## To Reproduce

update  to the latest version ("i18next": "^23.12.1",   "react-i18next": "^14.1.2")

```
export const RESOURCES_LANGUAGES = {
  en: {
    translation: en,
  },
} as const;
```

```
import 'i18next';
import { RESOURCES_LANGUAGES } from '@locale/index';

declare module 'i18next' {
  interface CustomTypeOptions {
    resources: typeof RESOURCES_LANGUAGES.en;
  }
}

```

## Expected behavior

The keys shown are all in my JSON file

## Your Environment

- *runtime version*: "react": "18.2.0", "node": ">=18", "typescript": "^5.5.3"
- *i18next version*:  "^23.12.1"  , "react-i18next": "^14.1.2",
- *os*: Mac

**Comment by adrai** [comment]
This seems to work: https://github.com/i18next/i18next/tree/master/examples/typescript

Please provide a minimal reproducible example repository...

**Comment by hieuminh1810** [comment]
> This seems to work: https://github.com/i18next/i18next/tree/master/examples/typescript
> 
> Please provide a minimal reproducible example repository...

- You can pls help me check this repo
       https://github.com/hieuminh1810/reproducible-example-i18next

- I added package.json, types, locale folder, eslintrc

**Comment by adrai** [comment]
Your screenshot shows, that it works as expected.... "thank_you" is listed

"thankou" is also listed, because you are using the "_" and that is used as pluralSeparator and contextSeparator character...

https://www.i18next.com/overview/typescript
<img width="644" alt="image" src="https://github.com/user-attachments/assets/8dd0eeae-c4c6-4a2f-a125-5dfa429fb3f0">

If you don't need that, just change that to a different separator:
<img width="419" alt="image" src="https://github.com/user-attachments/assets/89280532-dc3e-4d1e-af16-cc113b7c7189">

**Comment by hieuminh1810** [comment]
@adrai **tks you so much**
it work well ^__^
