### ISSUE TITLE
Return type of `t` function seems to change for some assignments

### ISSUE THREAD

**Issue by sebakerckhof** [i18next/i18next#2232]
## 🐛 Bug Report

In some cases the return type of the `t` function is `any` instead of `string`.
It seems like it depends on the type of the variable you assign it to.

This is incorrect and gives conflicts with common eslint rules, such as https://typescript-eslint.io/rules/no-unsafe-assignment/ , which are part of the default recommended eslint-typescript rules

## To Reproduce
https://codesandbox.io/p/sandbox/quiet-waterfall-cpfc45

or basically:
```js
import i18n from "./i18n";
const foo: Record<string, any> = {};
const bar = i18n.t("test"); // here `i18n.t` returns type 'string'
foo.bar = i18n.t("test"); //  here `i18n.t` returns type 'any'
```

![Screenshot from 2024-09-09 11-15-16](https://github.com/user-attachments/assets/961a94ca-67c8-43ec-971e-d444b7501d3e)

## Expected behavior
The return type should not change depending on the assignment and should in both cases be `string` in the example above.

## Your Environment

- *runtime version*: browser
- *i18next version*: i.e. 23.14.0
- *os*: Linux
- *any other relevant information*

**Comment by adrai** [comment]
if you or @marcalexiei has any idea of how to address this, feel free to provide a PR

**Comment by marcalexiei** [comment]
The example configuration is wrong: 
<details>
<summary> index has `js` extension rather than `ts` extension</summary>
<img width="968" alt="image" src="https://github.com/user-attachments/assets/a53c0bc9-82df-4678-bb3b-a49430db301d">
</details>

<details>
<summary>`.eslint.config.js` should be `eslint.config.js`</summary>

<img width="578" alt="image" src="https://github.com/user-attachments/assets/625961dd-9124-40c8-bc27-1f897035075f">

</details>

----

## Workaround

Recommended config includes `@typescript-eslint/no-explicit-any` which flags the `foo` declaration as `Record<string, any>`  which causes every key of `foo` to be `any`. So it is responsible for the wrong infer of `t` type.

> [!TIP]
> You should consider changing `any` to `string` or `unknown`. 

## Considerations

`TReturn` type has many type gymnastics involved, which makes `ts` to infer `any`  type as return type when assigning to an `any`. 
Using `NoInfer` could do the trick but these might break current behaviour (probably the defaultValue logic).
If anyone wants to try feel free to open a PR

**Comment by adrai** [comment]
@sebakerckhof try v23.15.1

**Comment by sebakerckhof** [comment]
Yep, works fine with latest version, thanks!
