### ISSUE TITLE
SetLng doesn't request new language.

### ISSUE THREAD

**Issue by boycce** [i18next/i18next#323]
Hey, It seems when `resStore` is defined and `setLang()` is triggered, no ajax requests are fired.

``` javascript
i18n.init({
  lng : 'en', 
  resGetPath : 'languages/__lng__.json',
  resStore : PreloadedEN

}, function(t) { 
  i18n.setLng('de');
}); 
```

**Comment by ganmor** [comment]
I am having the same problem.

Going throught the code in debug, it seems that when calling setLng, options are merged wiht the origin init options : 

```  
f.extend(o, options);
```
Options array happen to contain the original ressource store. So any additionnal language no be loaded. 


```
   if (o.resStore) {
            resStore = o.resStore;
            initialized = true;
            if (cb) cb(null, lngTranslate);
            if (deferred) deferred.resolve(lngTranslate);
            if (deferred) return deferred.promise();
            return;
        }
```

**Comment by jamuhl** [comment]
ah now i see. that's expected behaviour. If you pass in the resStore on init we expect you to handle all the resource loading (or to say correctly - we don't expect that resources could be loaded from server). If you pass no resStore data get loaded from server initial and on lng change.

you can use `addResourceBundle ` to add additional resources.
