### ISSUE TITLE
Serverside: jquery support

### ISSUE THREAD

**Issue by tuvistavie** [i18next/i18next#341]
Recent versions of i18next (> 1.7.4) seem to throw an exception when used with NodeJS.

```
var i18n = require('i18next');
i18n.init();
```

works perfectly well with 1.7.4, but throws an error with versions above:

```javascript
-> % node foo.js 

/home/daniel/tmp/bar/node_modules/i18next/lib/dep/i18next.js:1245
        $.fn.i18n = function (options) {
                  ^
TypeError: Cannot set property 'i18n' of undefined
    at addJqueryFunct (/home/daniel/tmp/bar/node_modules/i18next/lib/dep/i18next.js:1245:19)
    at init (/home/daniel/tmp/bar/node_modules/i18next/lib/dep/i18next.js:936:34)
    at Object.i18n.init (/home/daniel/tmp/bar/node_modules/i18next/lib/i18next.js:48:9)
    at Object.<anonymous> (/home/daniel/tmp/bar/foo.js:2:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Initializing with `setJqueryExt: false` does fix the problem, but I think
the `$.fn.i18n` part should not be evaluated if jQuery is not present.

**Comment by jamuhl** [comment]
why should one install jquery globally?

**Comment by tuvistavie** [comment]
A local installation will result in the same error.

**Comment by jamuhl** [comment]
i see now...sorry that it took me so long.

i will need to 'try' require('jquery') at https://github.com/i18next/i18next/blob/master/src/i18next.js#L6 to get this to work proper.

although i'm not sure why it appends the jquery function as https://github.com/i18next/i18next/blob/master/src/i18next.init.js#L64 checks if $ is defined (which is only set if there is jQuery on the global - which should not be the case i think)

but never mind:
- i will try to require('jquery') instead of depend on it being on root
- will add checks on the function if $ and $.fn exists (https://github.com/i18next/i18next/blob/master/src/i18next.jquery.js#L2)

**Comment by mathieumg** [comment]
> A local installation will result in the same error.

That's exactly what bit us. We use webpack and the jquery node module to package it for the front-end. In the same project's backend, we use i18next-node which wraps the i18next client.

Technically it shouldn't be a problem, but it is because of that: http://bugs.jquery.com/ticket/14549

If you don't need jQuery in the backend version, you could change [this line](https://github.com/i18next/i18next/blob/master/src/i18next.exports.js#L5) for 

```javascript
if (!$ && typeof window !== 'undefined') {
```

(Perhaps it could be put higher up in the branching, I just wanted to address the specificity of "that's when we try to require jQuery, unless we have no DOM")

If you do need the jQuery support in the backend, then I guess you'll need to provide it with a DOM like https://github.com/tmpvar/jsdom.

**Comment by jamuhl** [comment]
thanks for the additional information.

will change this for next version. makes sense...right now we exclude jquery in our web.pack.config....but honestly that should work without the need to configuration.

a PR might speed this up.

**Comment by mathieumg** [comment]
I don't mind making a PR but do you think the change I suggested would fit the bill or is there more to it? Thanks.

**Comment by jamuhl** [comment]
not looked to deep into it...but you might be right...not had the chance to test that deeper...

**Comment by jamuhl** [comment]
actually i wonder if we should create as main for the npm module a version without jquery. So default would be one without jquery and there is optional a file to require with jquery. (as there are two files for amd support).

later if we got more time and the time is ready i think we might remove jquery completely - and provide that in an additional file (for the one still using jquery in their applications)?

any opinions on this?

**Comment by ali-khabbaz** [comment]
i had to use jquery in my project (server-side), so: 
instead of : $ = require('jquery');
try this : 
var window = require('jsdom').jsdom().createWindow();
$ = require('jquery')(window);

**Comment by jamuhl** [comment]
@ali-khabbaz what if someone uses something different then jsdom?

i'm really not sure if there is a proper solution (but might be just me)?

**Comment by mathieumg** [comment]
> actually i wonder if we should create as main for the npm module a version without jquery. So default would be one without jquery and there is optional a file to require with jquery. (as there are two files for amd support).

I would support that. I think this should be an opt-in, or not there at all.

**Comment by jamuhl** [comment]
next version won't require jquery anylonger.

there will be a separate file: i18next.commonjs.withJquery.js that will require jquery

**Comment by mathieumg** [comment]
> next version won't require jquery anylonger.

That's even better than a simple fix, awesome! Thank you. :grin:

**Comment by edouardkombo** [comment]
Hello Guys, I'm having the same issue using npm, and the i18next latest version 1.7.10
https://www.npmjs.com/package/i18next

        $.fn.i18n = function (options) {
                  ^
TypeError: Cannot set property 'i18n' of undefined
    at addJqueryFunct (C:\wamp\www\xxx\myapp\node_modules\i18next\lib\dep\i18next.js:1245:19)
    at init (C:\wamp\www\xxx\myapp\node_modules\i18next\lib\dep\i18next.js:936:34)
    at Object.i18n.init (C:\wamp\www\xxx\myapp\node_modules\i18next\lib\i18next.js:49:9)
    at Object.<anonymous> (C:\wamp\www\xxx\myapp\app.js:13:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

I can see a merge has been done, but how can I fix it?

**Comment by edouardkombo** [comment]
Ok I've found the bug.

Please update your package on NPM.

**Comment by jamuhl** [comment]
this fix here was for 'i18next-client' and did not yet land in 18next module for node.js.

sorry for that...i'm on it to publish a new version for both client/node by this/next week.
