### ISSUE TITLE
Question: Sync init possible?

### ISSUE THREAD

**Issue by arve0** [i18next/i18next#488]
Is it possible to init i18next synchronously?

**Comment by jamuhl** [comment]
if you're using a backend that is async by design - like eg. the xhr backend....no

see: https://developers.google.com/web/updates/2012/01/Getting-Rid-of-Synchronous-XHRs

if you really need synchronous loading you can create a own backend - just copy https://github.com/i18next/i18next-xhr-backend and enable sync loading by setting https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L16 `x.open(data ? 'POST' : 'GET', url, 0);`

**Comment by arve0** [comment]
> if you're using a backend that is async by design - like eg. the xhr backend....no

My context is filesystem/node.

> if you really need synchronous loading you can create a own backend

OK, so in the node-fs-backend, doing [`readFile`](https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L15) and [`write`](https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L90) should do it? What about error handling without a callback? Throw?

**Comment by arve0** [comment]
I've opened this in the [node-fs-backend](https://github.com/i18next/i18next-node-fs-backend/issues/4).
