### ISSUE TITLE
Promise based API

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next#661]
Are there any plans to support a promise based API, such as:

``` javascript
i18next.init(...)
.then(i18next => {
    ...
});
```

I guess this would necessitate a Promise polyfill, but since many popular APIs such as `fetch` and `Service Workers` depend on promises, I think it's safe to add these days.

**Comment by jamuhl** [comment]
not planned...the way i would go is to pass in a Promise Implementation on init if want support for them.

But right now there is no plan for it...

**Comment by perrin4869** [comment]
Got it!

**Comment by isaachinman** [comment]
@jamuhl I'll comment here first instead of opening a new issue. In my opinion, it's pretty vital that the entire API be promisified. In building the NextJs example, I actually became confused as I did not expect callback-based methods.

Are you open to this? It's been awhile since I promisified a library, but as far as I remember, there are two options:

1. Simple option - wrap everything in some browser-friendly `util.promisify` polyfill.
2. Proper option - do an actual rewrite to return promises.

In general, you probably wouldn't want to eliminate callbacks before a major version bump, so if we want to do a minor release that adds promises, we'll need to maintain callbacks as well.

Let me know your thoughts.

**Comment by jamuhl** [comment]
@isaachinman we could add promises for sure...the time seems now to be ready with the async-await options.

Personally, I would prefer a solution where we return a promise from the functions accepting a callback as function argument -> what I would avoid is removing the callback option completely. (So, I wouldn't even remove them on a major version - callbacks are nice 🍝)

**Comment by isaachinman** [comment]
@jamuhl What do you think about [this pattern](https://codesandbox.io/s/vyjjrw4q10)? Just my first idea. Important to note that `callback` is going to be `undefined`. You probably already protect against that in the current implementation though.

**Comment by jamuhl** [comment]
@isaachinman perfect...callback can be undefined...as it's optional in all cases.

**Comment by isaachinman** [comment]
So it should be a one-liner fix for all methods. Do you want to take this one, or shall I? I don't have access to this repo to be able to reopen issues, but we can either reopen here or just create a new issue to track this.

**Comment by jamuhl** [comment]
Will try to look into it tomorrow...should have the time for it...

**Comment by isaachinman** [comment]
Okay. If you don't have time just let me know and I'll take care of it.

**Comment by jamuhl** [comment]
closing this again - will be in next major: https://github.com/i18next/i18next/issues/1129
