### ISSUE TITLE
Multiple plural forms numbers do not comply with gettext headers

### ISSUE THREAD

**Issue by eugen35** [i18next/i18next#687]
**Standart codes for arabic are 0,1,2,3,4,5:**
See: http://mlocati.github.io/cldr-to-gettext-plural-rules/
http://mlocati.github.io/cldr-to-gettext-plural-rules/

**Your codes are 0,1,2,3,11,100**

**Comment by jamuhl** [comment]
numbers are defined in https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L20

can't remember where we got those definitions from...but they are here for over 5 years. Not sure if i should switch over to just use the returned index instead of the numbers - which honestly i got no idea what they stand for...

might do a breaking change here...what do you think...i mean the rules are correct to return the index - which is the value eg. gettext uses. So obviously using the index instead of the nr would be more clear?

**Comment by jamuhl** [comment]
ok found the source again...the rules came from node-gettext...hm...and the numbers are just sample values as it seems....will do a breaking version switching over to use the index used by gettext.

**Comment by jamuhl** [comment]
changed in i18next@3.0.0
