### ISSUE TITLE
Tiny logger module initialization issue ;-)

### ISSUE THREAD

**Issue by npelletm** [i18next/i18next#880]
Here https://github.com/i18next/i18next/blob/master/src/i18next.js#L171, condition must be 
```
 if (module.type === 'logger' || (module.log && module.warn && module.error)) {
```

**Comment by jamuhl** [comment]
you just need to set type both on instance and class like eg. in backend https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L19
https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L82

**Comment by npelletm** [comment]
Thanks, it is not an issue, just a "pointer" for you

**Comment by jamuhl** [comment]
Ah...now i see...never looked at the code...wasn't aware i do the alternative check for having `(module.log && module.warn && module.error)` -> and there it checks twice for warn.

https://github.com/i18next/i18next/commit/1999026121d2fc8e78405e3cf46af8d0020d9a58 will be fixed in next version.

sorry for being that slow in getting the issue...
