### ISSUE TITLE
nesting and interpolation.format do not work well together

### ISSUE THREAD

**Issue by rally25rs** [i18next/i18next#977]
(using i18next v9.0.1)

If you have a custom format function, for example:

```
      interpolation: {
        format: function(value, format, lng) {
          if(format === 'downcase') {
            return value.toLowerCase();
          }
          return value;
        },
```

And you attempt to use it with a nested translation:

```
{
  hello: 'Hello',
  greeting: 'Hello {{name, downcase}}'
}

i18n.t('greeting', { name: '$t(hello)' });
```

This _should_ result in `Hello hello`.

However, it seems that the nested translation is not resolved before it is passed to `format`. The `format` function receives the parameters `('$t(hello)', 'downcase')`.

Then after the format function is called, the nested translation is resolved.

So `i18n.t('greeting', { name: '$t(hello)' });` results in `Hello Hello` instead of `Hello hello`.

**Comment by jamuhl** [comment]
why not just: `i18n.t('greeting', { name: t('hello') });`

doing those nestings inside vars is a little over the top. already once changed the execution order to do interpolation before nesting...not sure should we do it now configurable?

**Comment by rally25rs** [comment]
hah, yes, that works. thanks for pointing out that workaround.

**Comment by Czahoo** [comment]
Hey @jamuhl ,

I know 2 years have passed but I just encountered this case and unfortunately workaround you provided won't work for me. Is there any other way to make this work?

Maybe you could make order of nesting / interpolation configurable as you mentioned?

Or preferably `format` should operate on other terms, because from what I can think of formatting should always be the final step when parsing translation (cause you always want to format final values instead of ones that still needs computation).

What do you think?

**Comment by jamuhl** [comment]
@Czahoo those interpolation, formating and nesting are simple regex replacements...so not much combination possible there. Could you please paste your sample you like to do - code, result and expected result in a new issue - so I can check for possible solutions.
