### ISSUE TITLE
Alias 'lang' for 'lng'

### ISSUE THREAD

**Issue by moos** [i18next/i18next#983]
Don't mean to nitpick, but I'm finding it hard to warm-up to the `lng` abbreviation in config options (not to be confused with [LNG](http://www.abbreviations.com/LNG).  Would love to see the more common `lang` as an alias.

**Comment by jamuhl** [comment]
just scroll down lng stands for language too. both `lng` and `lang` are used.

so you might  have to get a little warm with it - not going the way and add extras for such cases...already to much configuration options in i18next.

**Comment by moos** [comment]
Most web devs are already quite familiar with 'lang' via [HTML](https://www.w3schools.com/tags/ref_language_codes.asp) and [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:lang).  Even worthwhile, IMHO, making a breaking change if you don't want to support both.  It's always good to improve the API and keep it fresh. 

Anyway, thanks for this work -- luckily don't have to deal with 'lng' much outside the initial config.

**Comment by jamuhl** [comment]
And the next want it do be locale instead of language - as it's not really a language but a complete iso code for locales `zh-Hant-HK`.

We use lng now for over 6 years. So while i agree lang would be valid too, or meanwhile more common used...i don't think it's worth the trouble. Might change in future if we get that request more often.
